require "bira.plugins.telescope"
require "bira.plugins.lualine"
require "bira.plugins.treesitter"
require "bira.plugins.cmp"
require "bira.plugins.nvimtree"
require "bira.plugins.bufferline"
require "bira.plugins.lazygit"
require "bira.plugins.null-ls"
-- require "bira.plugins.mini-starter"

